repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [ '--fix=lf' ]
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
        args: [ '--allow-multiple-documents' ]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: [ '--fix' ]
  - repo: https://github.com/adamchainz/blacken-docs
    rev: "1.16.0"  # replace with latest tag on GitHub
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==24.1.1
        args: [ '-l 76' ]
