baseURL = "https://suayip.dev"
languageCode = "en-us"
title = "şuayip üzülmez"
theme = "archie"
copyright = "© şuayip üzülmez"
# Code Highlight
pygmentsstyle = "github-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate = 5 # articles per page

[params]
mode = "dark" # color-mode → light,dark,toggle or auto
useCDN = true
subtitle = "Hello world!"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/realsuayip/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/realsuayip/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4